package loop

var panelLabels = map[string]map[string]string{
	"en": {
		"answer_placeholder": "Type your answer...",
		"answer_keys":        "ctrl+enter / alt+enter / ctrl+s send · esc cancel · enter newline",
		"answer_empty":       "The answer is empty.",

		"loop_run":    "loop ●",
		"loop_none":   "loop ○",
		"loop_stale":  "loop ○ stale",
		"loops":       "%d loops",
		"loop_stop":   "loop stopped",
		"pick":        "d picks another delivery",
		"context":     "Context",
		"progress":    "Progress",
		"detail":      "Detail",
		"table":       "Waves and tasks",
		"logs":        "Recent log",
		"waves":       "Waves",
		"tasks":       "Tasks",
		"sessions":    "sessions",
		"retries":     "retries",
		"escalations": "escalations",
		"keys":        "up/down PgUp/PgDn scroll · f follow active · r answer · o open log · ? legend · q quit watch",
		"keys_focus":  "up/down PgUp/PgDn scroll · l log · f follow active · r answer · o open log · ? legend · q quit watch",
		"above":       "above",
		"below":       "below",
		"running":     "running",
		"open":        "open",
		"integrated":  "integrated",
		"abandoned":   "abandoned",
		"canceled":    "canceled",
		"pending":     "pending",
		"before_run":  "before run",
		"executor":    "executor",
		"question":    "waiting answer",
		"limit":       "usage limit",
		"blocked":     "blocked",
		"conflict":    "re-executing",
		"escalated":   "escalated",
		"attempt":     "Attempt",
		"tr":          "Try",
		"status":      "Status",
		"gates":       "Gates",
		"commit":      "Commit",
		"id":          "ID",
		"task":        "Wave / Task",
		"criterion":   "Criterion",
		"last":        "Last",
		"reason":      "Reason",
		"worktree":    "Worktree",
		"log":         "Log",
		"needs_none":  "needs you: no",
		"tests":       "Tests",
		"base":        "base",
		"after":       "after",
		"resumes":     "resumes",
		"answer":      "r answers",
		"openlog":     "o opens the log",
		"phase":       "phase",
		"color_done":  "green · integrated",
		"color_run":   "blue · running",
		"color_fail":  "red · blocked",
		"color_wait":  "yellow · waiting answer",
		"color_pend":  "dim · pending",
		"color_pick":  "reverse · selected task",
		"ago":         "ago",
		"stale":       "stale",
	},
	"pt": {
		"answer_placeholder": "Digite sua resposta...",
		"answer_keys":        "ctrl+enter / alt+enter / ctrl+s envia · esc cancela · enter nova linha",
		"answer_empty":       "A resposta está vazia.",

		"loop_run":    "loop ●",
		"loop_none":   "loop ○",
		"loop_stale":  "loop ○ stale",
		"loops":       "%d loops",
		"loop_stop":   "loop parado",
		"pick":        "d escolhe outra entrega",
		"context":     "Contexto",
		"progress":    "Progresso",
		"detail":      "Detalhe",
		"table":       "Waves e tasks",
		"logs":        "Log recente",
		"waves":       "Waves",
		"tasks":       "Tasks",
		"sessions":    "sessões",
		"retries":     "retries",
		"escalations": "escalações",
		"keys":        "↑↓ PgUp/PgDn rolam · f segue a ativa · r responde · o abre o log · ? legenda · q sai do watch",
		"keys_focus":  "↑↓ PgUp/PgDn rolam · l log · f segue a ativa · r responde · o abre o log · ? legenda · q sai do watch",
		"above":       "acima",
		"below":       "abaixo",
		"running":     "em execução",
		"open":        "aberta",
		"integrated":  "integrada",
		"abandoned":   "abandonada",
		"canceled":    "cancelada",
		"pending":     "pendente",
		"before_run":  "antes do run",
		"executor":    "executor",
		"question":    "aguarda resposta",
		"limit":       "limite de uso",
		"blocked":     "bloqueada",
		"conflict":    "reexecutando",
		"escalated":   "escalada",
		"attempt":     "Tentativa",
		"tr":          "Tent.",
		"status":      "Status",
		"gates":       "Gates",
		"commit":      "Commit",
		"id":          "ID",
		"task":        "Wave / Task",
		"criterion":   "Critério",
		"last":        "Último",
		"reason":      "Motivo",
		"worktree":    "Worktree",
		"log":         "Log",
		"needs_none":  "precisa de você: não",
		"tests":       "Testes",
		"base":        "base",
		"after":       "após",
		"resumes":     "retoma",
		"answer":      "r responde",
		"openlog":     "o abre o log",
		"phase":       "fase",
		"color_done":  "verde · integrada",
		"color_run":   "azul · em execução",
		"color_fail":  "vermelho · bloqueada",
		"color_wait":  "amarelo · aguarda resposta",
		"color_pend":  "atenuado · pendente",
		"color_pick":  "invertido · task selecionada",
		"ago":         "atrás",
		"stale":       "obsoleto",
	},
}
