package loop

var panelLabels = map[string]map[string]string{
	"en": {
		"context":     "Context",
		"progress":    "Progress",
		"detail":      "Detail",
		"table":       "Waves and tasks",
		"logs":        "Recent log",
		"waves":       "Waves",
		"tasks":       "Tasks",
		"sessions":    "sessions",
		"retries":     "retries",
		"escalations": "escalations",
		"keys":        "up/down PgUp/PgDn scroll · f follow active · r answer · o open log · ? legend · q quit watch",
		"above":       "above",
		"below":       "below",
		"running":     "running",
		"integrated":  "integrated",
		"pending":     "pending",
		"before_run":  "before run",
		"executor":    "executor",
		"question":    "waiting answer",
		"limit":       "usage limit",
		"blocked":     "blocked",
		"conflict":    "re-executing",
		"escalated":   "escalated",
		"attempt":     "Attempt",
		"tr":          "Try",
		"status":      "Status",
		"gates":       "Gates",
		"commit":      "Commit",
		"id":          "ID",
		"task":        "Wave / Task",
		"criterion":   "Criterion",
		"last":        "Last",
		"reason":      "Reason",
		"worktree":    "Worktree",
		"log":         "Log",
		"needs_none":  "needs you: no",
		"tests":       "Tests",
		"base":        "base",
		"after":       "after",
		"resumes":     "resumes",
		"answer":      "r answers",
		"openlog":     "o opens the log",
		"phase":       "phase",
	},
	"pt": {
		"context":     "Contexto",
		"progress":    "Progresso",
		"detail":      "Detalhe",
		"table":       "Waves e tasks",
		"logs":        "Log recente",
		"waves":       "Waves",
		"tasks":       "Tasks",
		"sessions":    "sessões",
		"retries":     "retries",
		"escalations": "escalações",
		"keys":        "↑↓ PgUp/PgDn rolam · f segue a ativa · r responde · o abre o log · ? legenda · q sai do watch",
		"above":       "acima",
		"below":       "abaixo",
		"running":     "em execução",
		"integrated":  "integrada",
		"pending":     "pendente",
		"before_run":  "antes do run",
		"executor":    "executor",
		"question":    "aguarda resposta",
		"limit":       "limite de uso",
		"blocked":     "bloqueada",
		"conflict":    "reexecutando",
		"escalated":   "escalada",
		"attempt":     "Tentativa",
		"tr":          "Tent.",
		"status":      "Status",
		"gates":       "Gates",
		"commit":      "Commit",
		"id":          "ID",
		"task":        "Wave / Task",
		"criterion":   "Critério",
		"last":        "Último",
		"reason":      "Motivo",
		"worktree":    "Worktree",
		"log":         "Log",
		"needs_none":  "precisa de você: não",
		"tests":       "Testes",
		"base":        "base",
		"after":       "após",
		"resumes":     "retoma",
		"answer":      "r responde",
		"openlog":     "o abre o log",
		"phase":       "fase",
	},
}
