package review

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"
)

func gitTest(t *testing.T, root string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "GIT_CONFIG_GLOBAL="+os.DevNull, "GIT_AUTHOR_NAME=Review Test", "GIT_AUTHOR_EMAIL=review@example.test", "GIT_COMMITTER_NAME=Review Test", "GIT_COMMITTER_EMAIL=review@example.test")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
	return strings.TrimSpace(string(out))
}

func writeTestFile(t *testing.T, root, name, content string) {
	t.Helper()
	filename := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(filename), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filename, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
}

func reviewRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	gitTest(t, root, "init", "-q")
	gitTest(t, root, "-c", "commit.gpgsign=false", "commit", "-qm", "base", "--allow-empty")
	return root
}

func TestManifestAccountsForEveryFile(t *testing.T) {
	root := reviewRepo(t)
	for name, text := range map[string]string{
		"edit.go": "one\ntwo\nthree\nfour\n", "deleted.go": "gone\n",
		"old name.go": "unchanged rename\n", "generated-deleted.go": "// Code generated by test\n",
	} {
		writeTestFile(t, root, name, text)
	}
	gitTest(t, root, "add", ".")
	gitTest(t, root, "-c", "commit.gpgsign=false", "commit", "-qm", "fixture")
	base := gitTest(t, root, "rev-parse", "HEAD")
	writeTestFile(t, root, "edit.go", "one\nTWO\nthree\nfour\nfive\n")
	gitTest(t, root, "rm", "deleted.go", "generated-deleted.go")
	gitTest(t, root, "mv", "old name.go", "new name.go")
	ignored := map[string]string{
		"vendor/x.go": "vendored", "sub/vendor/x.go": "vendored", "node_modules/x.js": "vendored",
		"nested/node_modules/x.js": "vendored", "deps.lock": "lock", "go.sum": "lock", "sub/go.sum": "lock",
		"api.pb.go": "generated", "x_generated.go": "generated", "site.min.js": "generated",
		"dist/x.js": "generated", "sub/build/x.js": "generated", "header.go": "generated",
		"manual.go": "generated",
	}
	for name := range ignored {
		writeTestFile(t, root, name, "generated data\n")
	}
	writeTestFile(t, root, "header.go", "// Code generated by fixture\nbody\n")
	writeTestFile(t, root, "manual.go", "// DO NOT EDIT\nbody\n")
	writeTestFile(t, root, "binary.dat", "\x00\x01")
	writeTestFile(t, root, "odd\tname\n.go", "no trailing newline")
	gitTest(t, root, "add", ".")
	writeTestFile(t, root, "untracked.go", "first\nsecond")
	writeTestFile(t, root, "empty.go", "")
	writeTestFile(t, root, ".gitignore", "scratch/\n")
	writeTestFile(t, root, "scratch/local.go", "not part of delivery\n")
	before := gitTest(t, root, "status", "--porcelain=v1", "-uall")
	m, err := BuildManifest(root, base, nil, ManifestOptions{Worktree: true})
	if err != nil {
		t.Fatal(err)
	}
	if after := gitTest(t, root, "status", "--porcelain=v1", "-uall"); before != after {
		t.Fatal("manifest changed the repository")
	}
	if len(m.Files) != len(ignored)+9 {
		t.Fatalf("got %d files: %+v", len(m.Files), m.Files)
	}
	byPath := make(map[string]File)
	var paths []string
	for _, file := range m.Files {
		if _, exists := byPath[file.Path]; exists {
			t.Fatalf("duplicate file %q", file.Path)
		}
		byPath[file.Path] = file
		paths = append(paths, file.Path)
	}
	if !slices.IsSorted(paths) {
		t.Fatal("manifest paths are not sorted")
	}
	for name, reason := range ignored {
		if f := byPath[name]; !f.Ignored || f.IgnoreReason != reason || f.Selected {
			t.Errorf("%s: %+v, want ignored %s", name, f, reason)
		}
	}
	if f := byPath["edit.go"]; f.Added != 2 || f.Deleted != 1 || !reflect.DeepEqual(f.Hunks, []Hunk{{Start: 2, Count: 1}, {Start: 5, Count: 1}}) {
		t.Errorf("edit hunks/counts: %+v", f)
	}
	if f := byPath["deleted.go"]; f.Status != "D" || f.Deleted != 1 || !reflect.DeepEqual(f.Hunks, []Hunk{{Start: 0, Count: 0}}) {
		t.Errorf("deleted file: %+v", f)
	}
	if f := byPath["generated-deleted.go"]; f.IgnoreReason != "generated" || f.Deleted != 1 {
		t.Errorf("deleted generated file: %+v", f)
	}
	if f := byPath["new name.go"]; f.OldPath != "old name.go" || f.Added+f.Deleted != 0 {
		t.Errorf("rename: %+v", f)
	}
	if f := byPath["untracked.go"]; f.Status != "?" || f.Added != 2 || !reflect.DeepEqual(f.Hunks, []Hunk{{Start: 1, Count: 2}}) {
		t.Errorf("untracked file: %+v", f)
	}
	if !byPath["binary.dat"].Binary || byPath["empty.go"].Added != 0 || byPath["odd\tname\n.go"].Added != 1 {
		t.Fatal("binary, empty, or unusual path accounting failed")
	}
	again, err := BuildManifest(root, base, nil, ManifestOptions{Worktree: true})
	if err != nil || !reflect.DeepEqual(m, again) {
		t.Fatalf("nondeterministic manifest: %v", err)
	}
	selected, err := BuildManifest(root, base, []string{"edit.go"})
	if err != nil || len(selected.Files) != len(m.Files)-3 || len(selected.Cohorts) != 1 || !slices.Equal(selected.Cohorts[0].Files, []string{"edit.go"}) {
		t.Fatalf("selection/default untracked policy: %+v, %v", selected, err)
	}
}

func TestCohortsRespectLimits(t *testing.T) {
	root := reviewRepo(t)
	for i, lines := range []int{700, 500, 1, 0, 600, 600, 1} {
		writeTestFile(t, root, fmt.Sprintf("%02d.go", i), strings.Repeat("line\n", lines))
	}
	m, err := BuildManifest(root, "HEAD", nil, ManifestOptions{Worktree: true, CohortFiles: 2})
	if err != nil {
		t.Fatal(err)
	}
	want := [][]string{{"00.go", "01.go"}, {"02.go", "03.go"}, {"04.go", "05.go"}, {"06.go"}}
	seen := make(map[string]int)
	for i, cohort := range m.Cohorts {
		if cohort.ChangedLines > 1200 || len(cohort.Files) > 2 || i >= len(want) || !slices.Equal(cohort.Files, want[i]) {
			t.Fatalf("cohort %d: %+v", i, cohort)
		}
		for _, name := range cohort.Files {
			seen[name]++
		}
	}
	if len(m.Cohorts) != len(want) || len(seen) != 7 {
		t.Fatalf("incomplete cohorts: %+v", m.Cohorts)
	}
	for _, count := range seen {
		if count != 1 {
			t.Fatal("file assigned more than once")
		}
	}
	for i, cohort := range m.Cohorts {
		if cohort.Oversized {
			t.Fatalf("ordinary cohort %d marked oversized: %+v", i, cohort)
		}
	}
}

func TestOversizedFileGetsOwnCohort(t *testing.T) {
	root := reviewRepo(t)
	for name, lines := range map[string]int{
		"00.go": 700,
		"01.go": CohortLines + 1,
		"02.go": 500,
		"03.go": 700,
	} {
		writeTestFile(t, root, name, strings.Repeat("line\n", lines))
	}
	m, err := BuildManifest(root, "HEAD", nil, ManifestOptions{Worktree: true})
	if err != nil {
		t.Fatal(err)
	}
	want := []Cohort{
		{Files: []string{"00.go"}, ChangedLines: 700},
		{Files: []string{"01.go"}, ChangedLines: CohortLines + 1, Oversized: true},
		{Files: []string{"02.go", "03.go"}, ChangedLines: CohortLines},
	}
	if !reflect.DeepEqual(m.Cohorts, want) {
		t.Fatalf("cohorts = %+v, want %+v", m.Cohorts, want)
	}
}

func TestManifestRejectsInvalidInputs(t *testing.T) {
	root := reviewRepo(t)
	for _, base := range []string{"", "--output=oops", "missing-ref"} {
		if _, err := BuildManifest(root, base, nil); err == nil {
			t.Errorf("accepted base %q", base)
		}
	}
	if _, err := BuildManifest(root, "HEAD", []string{"../outside"}); err == nil {
		t.Fatal("accepted escaping selection")
	}
	if _, err := BuildManifest(root, "HEAD", []string{"absent.go"}); err == nil {
		t.Fatal("silently accepted nonexistent selection")
	}
	if _, err := BuildManifest(root, "HEAD", nil, ManifestOptions{CohortFiles: -1}); err == nil {
		t.Fatal("accepted negative cohort limit")
	}
}

func TestManifestAccountsForEveryFileRemovedFromIndex(t *testing.T) {
	root := reviewRepo(t)
	writeTestFile(t, root, "source.go", "old\n")
	gitTest(t, root, "add", ".")
	gitTest(t, root, "-c", "commit.gpgsign=false", "commit", "-qm", "source")
	gitTest(t, root, "rm", "--cached", "source.go")
	writeTestFile(t, root, "source.go", "new\n// DO NOT EDIT is only a marker on the first line\n")
	m, err := BuildManifest(root, "HEAD", nil, ManifestOptions{Worktree: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Files) != 1 || len(m.Cohorts) != 1 || !slices.Equal(m.Cohorts[0].Files, []string{"source.go"}) {
		t.Fatalf("staged deletion and untracked content must share one entry: %+v", m)
	}
	if f := m.Files[0]; !f.Untracked || f.Status != "D" || f.Deleted != 1 || f.Added != 2 || f.Ignored || m.Cohorts[0].ChangedLines != 3 {
		t.Fatalf("both sides of the change must be accounted for: %+v", m)
	}
}

func TestCohortsRespectDefaultFileLimitAndDeletions(t *testing.T) {
	root := reviewRepo(t)
	for i := 0; i <= CohortFiles; i++ {
		writeTestFile(t, root, fmt.Sprintf("file-%02d.go", i), "")
	}
	m, err := BuildManifest(root, "HEAD", nil, ManifestOptions{Worktree: true})
	if err != nil || len(m.Cohorts) != 2 || len(m.Cohorts[0].Files) != CohortFiles || len(m.Cohorts[1].Files) != 1 {
		t.Fatalf("default file limit: %+v, %v", m, err)
	}
	writeTestFile(t, root, "a.go", strings.Repeat("old\n", 700))
	writeTestFile(t, root, "b.go", strings.Repeat("old\n", 501))
	gitTest(t, root, "add", ".")
	gitTest(t, root, "-c", "commit.gpgsign=false", "commit", "-qm", "source")
	gitTest(t, root, "rm", "a.go", "b.go")
	m, err = BuildManifest(root, "HEAD", nil)
	if err != nil || len(m.Cohorts) != 2 || m.Cohorts[0].ChangedLines != 700 || m.Cohorts[1].ChangedLines != 501 {
		t.Fatalf("deletions must consume the line budget: %+v, %v", m, err)
	}
}

func TestManifestDoesNotFollowSymlink(t *testing.T) {
	root := reviewRepo(t)
	outside := filepath.Join(t.TempDir(), "external.go")
	if err := os.WriteFile(outside, []byte("// DO NOT EDIT\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "link.go")); err != nil {
		t.Fatal(err)
	}
	m, err := BuildManifest(root, "HEAD", nil, ManifestOptions{Worktree: true})
	if err != nil || len(m.Files) != 1 || m.Files[0].Ignored || m.Files[0].Added != 1 {
		t.Fatalf("symlink should review link target text, not external content: %+v, %v", m, err)
	}
}

func TestManifestHandlesSubmoduleGitlink(t *testing.T) {
	for _, change := range []string{"deleted", "changed", "added"} {
		t.Run(change, func(t *testing.T) {
			root := reviewRepo(t)
			sub := reviewRepo(t)
			writeTestFile(t, sub, "source.go", "old\n")
			gitTest(t, sub, "add", ".")
			gitTest(t, sub, "-c", "commit.gpgsign=false", "commit", "-qm", "submodule")
			old := gitTest(t, sub, "rev-parse", "HEAD")
			if change != "added" {
				gitTest(t, root, "update-index", "--add", "--cacheinfo", "160000,"+old+",module")
				gitTest(t, root, "-c", "commit.gpgsign=false", "commit", "-qm", "gitlink")
			}
			base := gitTest(t, root, "rev-parse", "HEAD")
			added, deleted := 1, 1
			switch change {
			case "deleted":
				gitTest(t, root, "update-index", "--force-remove", "module")
				added = 0
			default:
				if err := os.Mkdir(filepath.Join(root, "module"), 0755); err != nil {
					t.Fatal(err)
				}
				writeTestFile(t, sub, "source.go", "new\n")
				gitTest(t, sub, "add", ".")
				gitTest(t, sub, "-c", "commit.gpgsign=false", "commit", "-qm", "update")
				next := gitTest(t, sub, "rev-parse", "HEAD")
				gitTest(t, root, "update-index", "--add", "--cacheinfo", "160000,"+next+",module")
				if change == "added" {
					deleted = 0
				}
			}
			manifest, err := BuildManifest(root, base, nil)
			if err != nil {
				t.Fatal(err)
			}
			if len(manifest.Files) != 1 || len(manifest.Cohorts) != 1 {
				t.Fatalf("manifest=%+v", manifest)
			}
			file := manifest.Files[0]
			if file.Path != "module" || !file.Selected || file.Added != added || file.Deleted != deleted || len(file.Hunks) != 1 {
				t.Fatalf("gitlink accounting=%+v", file)
			}
		})
	}
}

func TestManifestFileReplacedByDirectory(t *testing.T) {
	for _, name := range []string{"pkg", "odd name", "quoted\"\tname", "café"} {
		t.Run(name, func(t *testing.T) {
			root := reviewRepo(t)
			writeTestFile(t, root, name, "old file\n")
			gitTest(t, root, "add", ".")
			gitTest(t, root, "commit", "-qm", "file")
			gitTest(t, root, "rm", "--", name)
			writeTestFile(t, root, name+"/a.go", "package child\nvar New = true\n")
			gitTest(t, root, "add", ".")
			manifest, err := BuildManifest(root, "HEAD", nil)
			if err != nil {
				t.Fatal(err)
			}
			if len(manifest.Files) != 2 {
				t.Fatalf("files = %+v", manifest.Files)
			}
			parent, child := manifest.Files[0], manifest.Files[1]
			if parent.Path != name || parent.Added != 0 || parent.Deleted != 1 || !slices.Equal(parent.Hunks, []Hunk{{Start: 0, Count: 0}}) {
				t.Errorf("deleted parent = %+v", parent)
			}
			if child.Added != 2 || child.Deleted != 0 || manifest.Cohorts[0].ChangedLines != 3 {
				t.Errorf("manifest = %+v", manifest)
			}
			prompt, err := BuildCohortPrompt(root, manifest, Cohort{Files: []string{name}}, "", nil)
			if err != nil {
				t.Fatal(err)
			}
			if strings.Contains(prompt, "package child") || strings.Contains(prompt, "Allowed new lines") || !strings.Contains(prompt, "-old file") {
				t.Fatalf("contaminated parent prompt: %s", prompt)
			}
		})
	}
}
